### ISSUE TITLE
Name Under Head

### ISSUE THREAD

**Issue by edwardcohen** [edwardcohen/celebmoji#2]
Please add the name of the person under their head. Use San Francisco font, in this format: "Name!"

For example, Kanye!, should be the name of the Kanye pack.

**Comment by edwardcohen** [comment]
Make font size 8 PX and make it bold

**Comment by edwardcohen** [comment]
Please fix the height. See: https://cl.ly/hScz

**Comment by edwardcohen** [comment]
align text left, instead of centered.

**Comment by alexei1118** [comment]
align left doesn't look good.

**Comment by alexei1118** [comment]
height problem will be fixed at #9. Close.
